# Generated by Django 4.2.5 on 2023-09-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=160)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('nome_empresa', models.CharField(max_length=160)),
                ('categoria_empresa', models.CharField(max_length=160)),
                ('quitado', models.BooleanField()),
                ('stand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.stand')),
            ],
        ),
    ]
