# Generated by Django 4.2.5 on 2023-10-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='imagem',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
