# Generated by Django 4.2.5 on 2023-10-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('stands', '0002_stand_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stand',
            name='esta_reservado',
            field=models.BooleanField(default=False),
        ),
    ]
