# Generated by Django 4.2.5 on 2023-10-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0004_alter_stand_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagem'),
        ),
    ]
