# Generated by Django 4.2.5 on 2023-10-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_empresa_faturamento'),
        ('stands', '0005_alter_stand_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.empresa'),
        ),
    ]
