# Generated by Django 4.2.5 on 2023-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0008_alter_stand_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='imagem',
            field=models.ImageField(blank=True, default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
