# Generated by Django 4.2.5 on 2023-10-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='stand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stands.stand'),
        ),
        migrations.DeleteModel(
            name='Stand',
        ),
    ]
