# Generated by Django 4.2.5 on 2023-10-22 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('reservas', '0002_alter_reserva_stand_delete_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.empresa'),
            preserve_default=False,
        ),
    ]
