# Generated by Django 4.2.5 on 2023-10-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('stands', '0003_stand_empresa_stand_esta_reservado'),
        ('reservas', '0003_reserva_data_reserva_reserva_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.empresa'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='stand',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='stands.stand'),
        ),
    ]
